spring:
  application:
    name: habit-tracker-api

  datasource:
    url: jdbc:postgresql://localhost:5432/habit_tracker
    username: postgres
    password: Sandra1996

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

server:
  port: 8080